### ISSUE TITLE
Parallelism not working

### ISSUE THREAD

**Issue by KingScooty** [michaelcontento/circleci-matrix#16] opened 2016-03-28 20:33 UTC
Parallelism isn't working.

I've got 2 containers enabled in Circle CI, and both containers run the tests for the first variable in the `env` section. All the others after are ignored.

If i disable multiple containers, and run the tests in the 1 container, all the tests for all the environments run in series, one after the other just fine.

**Comment by michaelcontento** [comment] 2016-11-02 21:02
Sorry for the bad news, but due to time constraints I'm no longer able to maintain this tools. 😞 
But thank you for using/trying this in the first place! 🎉

**Comment by michaelcontento** [comment] 2016-11-06 11:23
After if pushed c0fe6ab2c850e239e66e9b137bc91f148ecdc177, @jcfr and @thewtex, part of the scikit-build organization (https://github.com/scikit-build), wrote me a mail and they are here to keep circlci-matrix alive. 

I've re-opened this issue for them and please do give them a warm welcome 👏

**Comment by jcfr** [comment] 2016-11-07 03:26
@KingScooty Do you have minimal example allowing to reproduce the problem ? 

With a short example at hand, it allows us to understand and hopefully fix the issue while adding a new test to the project.

**Comment by michaelcontento** [comment] 2017-04-02 07:00
I'll close this issue as this could not be replicated and @KingScooty remained silence for a long time.

@KingScooty If this still broken for you, please re-open this issue and provide some more details (like a example `circleci-matrix.yml`).

**Closed as completed by michaelcontento** 2017-04-02 07:00 UTC
